[book]
description = "The official nekos.best API documentation."
language = "en"
multilingual = false
title = "nekos.best API"

[output.html]
default-theme = "navy"
cname = "docs.nekos.best"
git-repository-icon = "fa-github"
git-repository-url = "https://github.com/nekos-best/docs"

[output.html.print]
enable = false
